steps:
  # Create docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/demoimage:$SHORT_SHA", "."]
  # Push to container reg    
  - name: 'gcr.io/cloud-builders/docker'
    args: ["push", "gcr.io/${PROJECT_ID}/demoimage:$SHORT_SHA"]
  # deploy to cloud run
  - name: gcr.io/cloud-builders/gcloud
    args: ["run", "deploy", "demoimage", "--image", "gcr.io/${PROJECT_ID}/demoimage:${SHORT_SHA}", "--region", "us-central1", '--platform', 'managed']
